name: powermax_1rm
description: A premium, offline-first 1RM Calculator & AI Gym Coach in Flutter.
version: 1.18.1+12

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localisation
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State Management
  flutter_riverpod: ^2.5.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5

  # Image Picker
  image_picker: ^1.1.2

  # UI & Design
  google_fonts: ^6.2.1
  fl_chart: ^0.66.0
  shared_preferences: ^2.3.2
  system_info_plus: ^0.0.6
  flutter_markdown: ^0.7.4
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_no_background.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#0d0d0d" # Fondo oscuro premium que combina con tu tema
  adaptive_icon_foreground: "assets/logo_no_background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/default_routines.json
    - assets/pubspec.yaml
    - assets/logo.png
    - assets/logo_no_background.png
