// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWMRsVHcSor7f4_zMLNPNfnsNdX0i2uOk',
    appId: '1:496214612938:web:c5a29b8df6ad799fa50d33',
    messagingSenderId: '496214612938',
    projectId: 'powermax-1rm',
    authDomain: 'powermax-1rm.firebaseapp.com',
    storageBucket: 'powermax-1rm.firebasestorage.app',
    measurementId: 'G-WMFTSGFCEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcXADxSVWHisfaJwZ_-KvM2MIfhty0XEQ',
    appId: '1:496214612938:android:f443b9f032ea55cea50d33',
    messagingSenderId: '496214612938',
    projectId: 'powermax-1rm',
    storageBucket: 'powermax-1rm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxW6x4HupH3PPSAQ3w1lGoYMZXjYn-5LM',
    appId: '1:496214612938:ios:aea8fed9823652ada50d33',
    messagingSenderId: '496214612938',
    projectId: 'powermax-1rm',
    storageBucket: 'powermax-1rm.firebasestorage.app',
    iosBundleId: 'com.example.powermax1rm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxW6x4HupH3PPSAQ3w1lGoYMZXjYn-5LM',
    appId: '1:496214612938:ios:aea8fed9823652ada50d33',
    messagingSenderId: '496214612938',
    projectId: 'powermax-1rm',
    storageBucket: 'powermax-1rm.firebasestorage.app',
    iosBundleId: 'com.example.powermax1rm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWMRsVHcSor7f4_zMLNPNfnsNdX0i2uOk',
    appId: '1:496214612938:web:10dadd35414790c2a50d33',
    messagingSenderId: '496214612938',
    projectId: 'powermax-1rm',
    authDomain: 'powermax-1rm.firebaseapp.com',
    storageBucket: 'powermax-1rm.firebasestorage.app',
    measurementId: 'G-H727R5ES44',
  );
}
